### PR TITLE
fix shared store

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: all files reviewed, 6 unresolved discussions (waiting on @MarcusSorealheis)

___
*[`cas/store/shard_store.rs` line 1 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeysuJv7vKd-rfuJ0HB:-NeysuJw4a79Q3OLQCiF:b-jitiyz) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

Nit date should be 2023
___
*[`cas/store/shard_store.rs` line 36 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeytxwD5dmovLMtxMYO:-NeytxwED5kEQyBP5z8i:b6z9xhy) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L36)):*
> ```XML
> impl ShardStore {
>     pub fn new(config: &config::stores::ShardStore, stores: Vec<Arc<dyn StoreTrait>>) -> Result<Self, Error> {
>         error_if!(
> ```

Can we add another check to make sure at least 1 sore is configured?
___
*[`cas/store/shard_store.rs` line 94 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeyuXI2CanWcHGhc7PI:-NeyuXI2CanWcHGhc7PJ:bvo5074) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L94)):*
> ```XML
>             // Hot path: It is very common to lookup only one digest.
>             let store = self.get_store(&digests[0]);
>             store.has_with_results(digests, results).await?;
> ```

Nit just return this result instead of return on next line.
___
*[`cas/store/shard_store.rs` line 97 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeyufzwC4etrVRZnrLO:-NeyufzwC4etrVRZnrLP:bg53y61) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L97)):*
> ```XML
>             return Ok(());
>         }
>         let mut digests_for_store: Vec<_> = self
> ```

Nit can we spell out the type here and comment on what each vector is?
___
*[`config/stores.rs` line 101 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeywjAn3yuAygq1PfTj:-NeywjAn3yuAygq1PfTk:buqov25) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/config/stores.rs#L101)):*
> ```XML
>     /// The digest hash is used to determine which store to send the
>     /// data to.
>     shard(Box<ShardStore>),
> ```

Nit, I don't think this needs to be in a box.
___
*[`config/stores.rs` line 142 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-Neywofg4VjFLbvyemX8:-Neywofg4VjFLbvyemX9:bdu3ojn) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/config/stores.rs#L142)):*
> ```XML
> #[derive(Serialize, Deserialize, Debug, Clone)]
> pub struct ShardConfig {
>     /// Sore to shard the data to.
> ```

Nit: Store*

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-:-Neyx6dl5PfLRup6EQyv:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @MarcusSorealheis)

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/store/shard_store.rs` line 1 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeysuJv7vKd-rfuJ0HB:-Nf3lXPX87Lj9BfvkTQa:bb7f2mf) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit date should be 2023
</blockquote></details>

done
___
*[`cas/store/shard_store.rs` line 36 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeytxwD5dmovLMtxMYO:-Nf3ldd49aBFJvD85Sez:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L36)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we add another check to make sure at least 1 sore is configured?
</blockquote></details>

Done.
___
*[`cas/store/shard_store.rs` line 94 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeyuXI2CanWcHGhc7PI:-Nf3ljpp24Fo4imoqG5s:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L94)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit just return this result instead of return on next line.
</blockquote></details>

Done.
___
*[`cas/store/shard_store.rs` line 97 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeyufzwC4etrVRZnrLO:-Nf3mgg-51QGL1nRwpoA:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/cas/store/shard_store.rs#L97)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit can we spell out the type here and comment on what each vector is?
</blockquote></details>

Done.
___
*[`config/stores.rs` line 101 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-NeywjAn3yuAygq1PfTj:-Nf3mixsBmgWFkGaFJDH:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/config/stores.rs#L101)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit, I don't think this needs to be in a box.
</blockquote></details>

Done.
___
*[`config/stores.rs` line 142 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/293#-Neywofg4VjFLbvyemX8:-Nf3mjvCBFPLRsk35SCQ:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/19523b3ae3313468d37e2f5fcb7b7a3bf5542b8f/config/stores.rs#L142)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit: Store*
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Pull request merged**
