### PR TITLE
Future proof code from accidentially creating zombies

### PR DESCRIPTION
**Pull request by allada**
Move to use scopeguard instead of drop_guard and move workers so code changes make zombies significantly less likely.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/280)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/280#-:-NeFp0xB3HlR7VSwSKu3:b96vhr1)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Comment by chrisstaite-menlo** [comment]
Reviewable appears to have broken with the organisation change:
```
Failed to publish: GitHub error 403 on POST https://api.github.com/repos/tracemachina/turbo-cache/pulls/280/reviews: Although you appear to have the correct authorization credentials, the `TraceMachina` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

**Comment by allada** [comment]
Yep sorry about that. Try now.

**Comment by chrisstaite-menlo** [comment]
Nope, still not working.

**Review by allada — COMMENTED** [review]
How about now?

> *[Reviewable](https://reviewable.io/reviews/tracemachina/turbo-cache/280#-:-NeIfzxn7xzwyMeBRWnt:begw0lt)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/turbo-cache/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by chrisstaite-menlo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/turbo-cache/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/turbo-cache/280)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 716 at r1](https://reviewable.io/reviews/tracemachina/turbo-cache/280#-NeOQxpPDZtA7skHDcSN:-NeOQxpPDZtA7skHDcSO:bevegzo) ([raw file](https://github.com/tracemachina/turbo-cache/blob/fc80027d12d6dd4fefb41f801e9ff5e4fa9f0eb3/cas/worker/running_actions_manager.rs#L716)):*
> ```XML
>                     }
>                 },
>                 maybe_exit_status = child_process_guard.wait() => {
> ```

todo: If this triggers, it needs to consume `child_process_guard`, or the destructor will run.

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/turbo-cache/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
