### PR TITLE
Prometheus now publishes number of clients connected since server started and the timestamp when the server starts

### PR DESCRIPTION
**Pull request by blakehatch**
#206 

Total ip/ports that have connected since server started are published in prometheus now for each service.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)

### CODE REVIEW

**Comment by blakehatch** [comment]
- Seems as though similar PRs did not have a test suite would love guidance on what sufficient testing looks like for these Prometheus related tasks.
- Counter from Prometheus had a conflict with the custom metrics_utils Counter so had to rename. LSP wasn't showing that Counter was unused can remove the prometheus counter and revert back to the old naming to clean this up.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @blakehatch)

___
*[`cas/cas_main.rs` line 122 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCQCg7jkURBH03yNe:-NfNCQCg7jkURBH03yNf:bky2xqj) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/cas/cas_main.rs#L122)):*
> ```XML
>     /// report metrics about what clients are connected.
>     struct ConnectedClientsMetrics {
>         inner: Mutex<HashSet<SocketAddr>>,
> ```

nit: Just store the counter here. This is already sharable around.
___
*[`cas/cas_main.rs` line 138 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfND4Zf78G4GLejwjmA:-NfND4Zf78G4GLejwjmB:b-2ypexf) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/cas/cas_main.rs#L138)):*
> ```XML
> 
>             // Record the total number of client connections
>             let total_connections = TOTAL_CLIENT_CONNECTIONS.get();
> ```

nit: You could pass this directly into the `.publish` and it should work.
___
*[`cas/cas_main.rs` line 389 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCaKR6KUlFCjY6VYJ:-NfNCaKR6KUlFCjY6VYK:bngmy8a) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/cas/cas_main.rs#L389)):*
> ```XML
>                 let (tcp_stream, remote_addr) = tcp_listener.accept().await?;
>                 connected_clients_mux.inner.lock().insert(remote_addr);
>                
> ```

nit: needless spaces.
___
*[`tools/cargo_shared.bzl` line 130 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCgZs1KbYwEOtuK0q:-NfNCgZs1KbYwEOtuK0r:b-g0aybd) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/tools/cargo_shared.bzl#L130)):*
> ```Starlark
>         "version": "0.21.2",
>     },
>     "lazy_static": {
> ```

nit: Needless change.
___
*[`util/metrics_utils.rs` line 439 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCx1U8W8l-S0P13wy:-NfNCx1V-xrX8OaVPoaU:b-egyr7n) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/util/metrics_utils.rs#L439)):*
> ```XML
> /// Tracks an number.
> #[derive(Default)]
> pub struct MUCounter(AtomicU64);
> ```

nit: I do not recommend re-naming this in this PR. Normally renames should be separate PRs.
___
*[`util/metrics_utils.rs` line 464 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCucR3_yWdgTaoqFt:-NfNCucR3_yWdgTaoqFu:bhpznku) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/util/metrics_utils.rs#L464)):*
> ```XML
> 
>     #[inline]
>     pub fn get(&self) -> u64 {
> ```

nit: This is not needed.

**Comment by blakehatch** [comment]
Made all of the above changes except not fully understanding why the getter is not needed.

**Comment by blakehatch** [comment]
Also added publishing timestamp for server starting, can move to a separate PR if preferred.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)* status: 6 of 9 files reviewed, 8 unresolved discussions (waiting on @blakehatch)

*[a discussion](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRJfJF0IVpm_t78HFo:-NfRJfJF0IVpm_t78HFp:bsg9qeq) (no related file):*
You'll need to re-run: `python3 tools/build_cargo_manifest.py` after you change `BUILD` files, it is currently out-of-date.

___
___
*[`cas/cas_main.rs` line 118 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRIlt74KjUSQHrBalp:-NfRIlt74KjUSQHrBalq:bing153) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/cas_main.rs#L118)):*
> ```XML
>     struct ConnectedClientsMetrics {
>         inner: Mutex<HashSet<SocketAddr>>,
>         counter: Arc<Counter>,
> ```

nit: `ConnectedClientsMetrics` is already an `Arc`, so it's already sharable, there's no need to wrap the counter in an `Arc`.
___
*[`cas/cas_main.rs` line 119 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRIZ2M7Igc1f3dxr-x:-NfRIZ2M7Igc1f3dxr-y:b-pkesds) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/cas_main.rs#L119)):*
> ```XML
>         inner: Mutex<HashSet<SocketAddr>>,
>         counter: Arc<Counter>,
>         start: String, 
> ```

nit: I suggest using a timestamp instead. (don't forget to rename the field `server_start_ts`)
___
*[`cas/cas_main.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRJ-vP50KyyIsP8bny:-NfRJ-vP50KyyIsP8bnz:b64l442) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/cas_main.rs#L123)):*
> ```XML
>     impl MetricsComponent for ConnectedClientsMetrics {
>         fn gather_metrics(&self, c: &mut CollectorState) {
>             // Include the server start time metric
> ```

nit: End comment in period.
___
*[`cas/cas_main.rs` line 140 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRJ1e_Alj6ywncBkUa:-NfRJ1e_Alj6ywncBkUb:b64l442) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/cas_main.rs#L140)):*
> ```XML
>             }
> 
>             // Record the total number of client connections
> ```

nit: End comment in period.
___
*[`cas/cas_main.rs` line 147 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRJ3I-8RMuIGoYvcC4:-NfRJ3I-8RMuIGoYvcC5:bw0qctm) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/cas_main.rs#L147)):*
> ```XML
>                 &total_connections,
>                 "Total client connections since server started",
>             );        
> ```

nit: Spaces at end of line.
___
*[`cas/worker/BUILD` line 79 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRJWrP5Nb13u5xV-Op:-NfRJWrP5Nb13u5xV-Oq:b-g0aybd) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/2ae1a10ebc75989b71d976c7e0491ea66c2c4c08/cas/worker/BUILD#L79)):*
> ```Starlark
>         "//proto",
>         "@crate_index//:tonic",
>         "@crate_index//:prometheus-client",
> ```

nit: Needless change.
___
*[`util/metrics_utils.rs` line 464 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfNCucR3_yWdgTaoqFt:-NfRJGJS4Zd8ZxlLkPHk:b-6wjb9t) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/b88553e9677201418c0707ade627122966e5a5a0/util/metrics_utils.rs#L464)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is not needed.
</blockquote></details>

I still don't think this is needed, you should be able to pass the `Counter` directly into `.publish()`

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @blakehatch)

___
*[`cas/cas_main.rs` line 123 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRkCjT40DnrSMAParP:-NfRkCjT40DnrSMAParQ:bzdna8p) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/7f52790c11effb7b50fdf9d514a04dfc6943338a/cas/cas_main.rs#L123)):*
> ```XML
>     impl MetricsComponent for ConnectedClientsMetrics {
>         fn gather_metrics(&self, c: &mut CollectorState) {
>             // Include the server start time metric.
> ```

fyi: In future, no need for a comment when the code itself is clear what it is doing.
___
*[`cas/cas_main.rs` line 140 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRkDAD-rtGXJRGv1D0:-NfRkDAD-rtGXJRGv1D1:b-rqxvo7) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/7f52790c11effb7b50fdf9d514a04dfc6943338a/cas/cas_main.rs#L140)):*
> ```XML
>             }
> 
>             // Record the total number of client connections.
> ```

ditto.
___
*[`cas/cas_main.rs` line 164 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRkEZB8DxwbO5Y9Czr:-NfRkEZB8DxwbO5Y9Czs:b-fq1yi6) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/7f52790c11effb7b50fdf9d514a04dfc6943338a/cas/cas_main.rs#L164)):*
> ```XML
>             let connected_clients_mux = Arc::new(ConnectedClientsMetrics {
>                 inner: Mutex::new(HashSet::new()),
>                 counter: Into::into(Counter::default()),
> ```

nit: Needless `Into` (clippy would have caught this if it was ran under bazel).
___
*[`cas/cas_main.rs` line 165 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/298#-NfRkMztEedF-ybSqR_U:-NfRkMztEedF-ybSqR_V:btta0fu) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/7f52790c11effb7b50fdf9d514a04dfc6943338a/cas/cas_main.rs#L165)):*
> ```XML
>                 inner: Mutex::new(HashSet::new()),
>                 counter: Into::into(Counter::default()),
>                 server_start_ts: server_start_timestamp.clone(),
> ```

nit: `u64` implements `Copy` trait, so `Clone` is needless.

**Review by allada — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blakehatch)

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blakehatch)

**Pull request merged**
