### PR TITLE
Message field can now be populated with useful messages

### LINKED ISSUE #331: Remove Response Message from Action Messages
Remove Response Message from action_messages.rs

### LINKED ISSUE #333: Populate "message" field to a link to give users additional context about why something failed
Replace removed messages in #332 with useful outputs

### PR DESCRIPTION
**Pull request by allada**
We now allow users to configure how the message field is populated for ActionResult and added HistoricalExecuteResponse that is compatible with bb_browswer.

closes #333
closes #331

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@aaronmondal 
cc: @chrisstaite-menlo (feel free to review too if you'd like)

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-:-Ni3VjEQBdyFZN7b-kRo:b-y1hj5p)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361)* status: all files reviewed, 8 unresolved discussions (waiting on @allada)

___
*[`cas/cas_main.rs` line 501 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4s8i3DORV0s85Axcf:-Ni4s8i3DORV0s85Axcg:b66tina) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/cas_main.rs#L501)):*
> ```XML
>                     let maybe_ac_store = if let Some(ac_store_ref) = &local_worker_cfg.upload_action_result.ac_store {
>                         Some(store_manager.get_store(ac_store_ref).err_tip(|| {
>                             format!("Failed to find store for ac_store in worker config : {}", ac_store_ref)
> ```

nit:  `ac_store_ref` can be inlined:`format!("Failed to find ... {ac_store_ref}")`
___
*[`cas/cas_main.rs` line 512 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4rbWkBf53CeRWiKEY:-Ni4rbWl8jeRo8yJ-8AL:b-o9oxsc) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/cas_main.rs#L512)):*
> ```XML
>                             store_manager.get_store(cas_store_ref).err_tip(|| {
>                                 format!(
>                                     "Failed to find store for historical_results_store in worker config : {}",
> ```

nit:  `cas_store_ref` can be inlined:`format!("Failed to find ... {cas_store_ref}")`
___
*[`cas/worker/running_actions_manager.rs` line 1181 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4wrplCf8QaKjiNB6L:-Ni4wrpm0h78_ES7S838:b-3v9ewj) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1181)):*
> ```XML
>         if treat_infra_error_as_failure && action_result.error.is_some() {
>             did_fail = true;
>         }
> ```

Nit: You could remove the `mut` here



_Suggestion:_
```XML
        let did_fail = if treat_infra_error_as_failure && action_result.error.is_some() {
            true
        } else {
            action_result.exit_code != 0
        };
```
___
*[`cas/worker/running_actions_manager.rs` line 1187 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4yGaTCl6fF191Um6_:-Ni4yGaTCl6fF191Um6a:b9geb41) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1187)):*
> ```XML
>             // Never cache internal errors or timeouts.
>             UploadCacheResultsStrategy::Everything => treat_infra_error_as_failure || action_result.error.is_none(),
>             UploadCacheResultsStrategy::FailuresOnly => did_fail,
> ```

BTW Interesting. What is the use case for the `FailuresOnly` strategy?
___
*[`cas/worker/running_actions_manager.rs` line 1199 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4yzY46vmuvGw88Bxx:-Ni4yzY46vmuvGw88Bxy:b-msb1wy) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1199)):*
> ```XML
>     ) -> Result<String, Error> {
>         // TODO(allada) Currently only sha256 is supported, but soon will be dynamic.
>         template_str.replace("digest_function", digest_function::Value::Sha256.as_str_name());
> ```

Nit Do we really want to use SHA256 as the default over Blake3?
___
*[`cas/worker/running_actions_manager.rs` line 1235 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni5-owbBy7xkH1Yk9SO:-Ni5-owbBy7xkH1Yk9SP:b-exejtk) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1235)):*
> ```XML
>                 .update_action_result(Request::new(update_action_request))
>                 .await
>                 .map(|_| ())
> ```

Is this safe to do? What are we mapping to `()` here?
___
*[`cas/worker/running_actions_manager.rs` line 1285 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni51GOD7L-ibowJtbQ9:-Ni51GOD7L-ibowJtbQA:bnkc1tt) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1285)):*
> ```XML
>         let mut execute_response = to_execute_response(action_result.clone());
> 
>         let message_template = if action_result.exit_code == 0 && action_result.error.is_none() {
> ```

Could you add a comment explaining in what situation we could we get an exit code 0 and a not-none error message?
___
*[`cas/worker/running_actions_manager.rs` line 1325 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni526Ua2wwp6WtqOsE-:-Ni526Ua2wwp6WtqOsE0:b-eztxo2) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1325)):*
> ```XML
>             )
>             .await
>             .map(|_| ())
> ```

What are we mapping here?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronmondal)

___
*[`cas/cas_main.rs` line 501 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4s8i3DORV0s85Axcf:-Ni5VufnDoMhwJn8uwRI:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/cas_main.rs#L501)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit:  `ac_store_ref` can be inlined:`format!("Failed to find ... {ac_store_ref}")`
</blockquote></details>

Done.
___
*[`cas/cas_main.rs` line 512 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4rbWkBf53CeRWiKEY:-Ni5VvQa-oQO9WmYrzFt:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/cas_main.rs#L512)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit:  `cas_store_ref` can be inlined:`format!("Failed to find ... {cas_store_ref}")`
</blockquote></details>

Done.
___
*[`cas/worker/running_actions_manager.rs` line 1181 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4wrplCf8QaKjiNB6L:-Ni5WA8UCfoFHynDxzJU:b-fkhyxc) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1181)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Nit: You could remove the `mut` here
</blockquote></details>

Yeah I thought about it, but it was easier to read this way.
___
*[`cas/worker/running_actions_manager.rs` line 1187 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4yGaTCl6fF191Um6_:-Ni5WLaxAsZU0rGDOWGX:b-5cdf4f) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1187)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

BTW Interesting. What is the use case for the `FailuresOnly` strategy?
</blockquote></details>

Buildbarn uploads historical cache only on failure and uses action cache only on success when printing results.
___
*[`cas/worker/running_actions_manager.rs` line 1199 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni4yzY46vmuvGw88Bxx:-Ni5W_a_54c6HIXBf5e2:b-zec68z) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1199)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Nit Do we really want to use SHA256 as the default over Blake3?
</blockquote></details>

For now we don't support blake3 as a CAS hash function. This needs to be compatible with CAS for now so we need to stick to sha256.
___
*[`cas/worker/running_actions_manager.rs` line 1235 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni5-owbBy7xkH1Yk9SO:-Ni5Wj_u-FCWYmvSXpwO:b1to1bs) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1235)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this safe to do? What are we mapping to `()` here?
</blockquote></details>

This only ignores the `ActionResult`, which we don't care about here. The errors are not caught under `map()`, so errors are ignored.
___
*[`cas/worker/running_actions_manager.rs` line 1285 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni51GOD7L-ibowJtbQ9:-Ni5XS9P-qYLhJmWNSlF:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1285)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Could you add a comment explaining in what situation we could we get an exit code 0 and a not-none error message?
</blockquote></details>

Done.
___
*[`cas/worker/running_actions_manager.rs` line 1325 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni526Ua2wwp6WtqOsE-:-Ni5Xfq9Cm8PC3ruXgrK:b7h0qne) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/149ca6f8e87b1c38f2c73df107234084a8ba1529/cas/worker/running_actions_manager.rs#L1325)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

What are we mapping here?
</blockquote></details>

Yeah this map was needless.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-:-Ni77jJEDXT-hoqf-twb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 18 of 20 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/grpc_service/execution_server.rs` line 170 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni9WBFH6HLYTY2yrxnB:-Ni9WBFH6HLYTY2yrxnC:byn5mfq) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/cccd483485262261948347deaa5ef1be69e85097/cas/grpc_service/execution_server.rs#L170)):*
> ```XML
>         let receiver_stream = Box::pin(WatchStream::new(receiver).map(|action_update| {
>             log::info!("\x1b[0;31mexecute Resp Stream\x1b[0m: {:?}", action_update);
>             Ok(Into::<Operation>::into(action_update.as_ref().clone()))
> ```

Wouldn't `.into::<Operation>()` read better?
___
*[`cas/worker/local_worker.rs` line 248 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni9Wc-I3QBeICTWp4fW:-Ni9Wc-I3QBeICTWp4fX:bb70w76) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/cccd483485262261948347deaa5ef1be69e85097/cas/worker/local_worker.rs#L248)):*
> ```XML
>                                         // Save in the action cache before notifying the scheduler that we've completed.
>                                         if let Some(digest_info) = action_digest.clone().and_then(|action_digest| action_digest.try_into().ok()) {
>                                             if let Err(err) = running_actions_manager.cache_action_result(digest_info, &mut action_result).await {
> ```

Nice
___
*[`cas/worker/tests/utils/mock_running_actions_manager.rs` line 133 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni9XBmJ8sNvY4I2Bq1s:-Ni9XBmJ8sNvY4I2Bq1t:b-sg6bd6) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/cccd483485262261948347deaa5ef1be69e85097/cas/worker/tests/utils/mock_running_actions_manager.rs#L133)):*
> ```XML
>             .send(RunningActionManagerCalls::CacheActionResult(Box::new((
>                 action_digest,
>                 action_result.clone(),
> ```

Oh, not as nice as I first thought...

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/grpc_service/execution_server.rs` line 170 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/361#-Ni9WBFH6HLYTY2yrxnB:-NiAWIlx0W37jHWuS32b:b-gnqdkq) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/cccd483485262261948347deaa5ef1be69e85097/cas/grpc_service/execution_server.rs#L170)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Wouldn't `.into::<Operation>()` read better?
</blockquote></details>

Yeah, I go back and forth with this.

**Pull request merged**
