### PR TITLE
Added existence cache

### LINKED ISSUE #357: Implement existance cache store
This store should make it so calls to `.has()` are cached, but not the content. This is useful because some API calls only ensure things exist, but don't actually read the content.

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Added an existence cache for caching calls to has and whether the action exists or not, does not store the content.

Fixes #357

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Tested whether calls to has or walking the tree populate the existence cache properly.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)

### CODE REVIEW

**Review by steed924 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @blakehatch)

___
*[`cas/store/BUILD` line 503 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NieuKpn5JtTZnLWrgYR:-NieuKpn5JtTZnLWrgYS:b-mddbsb) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/BUILD#L503)):*
> ```Starlark
>         "@crate_index//:tokio",
>     ],
> )
> ```

Need a line break here.
___
*[`cas/store/verify_store.rs` line 272 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NieurMY31nYm7TK4ShU:-NieurMY31nYm7TK4ShV:b-7ropln) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/verify_store.rs#L272)):*
> ```XML
>         );
>     }
> }
> ```

ditto
___
*[`cas/store/tests/verify_store_test.rs` line 490 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Niev3BN-B7qlhlDhz4a:-Niev3BN-B7qlhlDhz4b:b-7ropln) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/tests/verify_store_test.rs#L490)):*
> ```XML
>         Ok(())
>     }
> }
> ```

ditto

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @blakehatch and @steed924)

___
*[`cas/store/verify_store.rs` line 15 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif7zg05V36VQqZ4MNC:-Nif7zg05V36VQqZ4MND:bskx5wh) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L15)):*
> ```XML
> // limitations under the License.
> 
> use std::collections::HashSet;
> ```

nit: Use:
https://docs.rs/hashbrown/latest/hashbrown/hash_set/struct.HashSet.html
___
*[`cas/store/verify_store.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8v7j85Zl6gGZ3TGT:-Nif8v7j85Zl6gGZ3TGU:bi8ba2o) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L47)):*
> ```XML
>         VerifyStore {
>             inner_store,
>             existence_cache: Mutex::new(HashSet::new()),
> ```

nit: I don't think we want to do existence cache in this store, it should be it's own store.
___
*[`cas/store/verify_store.rs` line 55 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif91V_AkiEboAJERRE:-Nif91V_AkiEboAJERRF:bpg7ddw) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L55)):*
> ```XML
>     }
> 
>     pub async fn record_existence_directory_walk(
> ```

This is never called.
___
*[`cas/store/verify_store.rs` line 189 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8akE7paMwiRD5RqW:-Nif8akE7paMwiRD5RqX:bonbxni) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L189)):*
> ```XML
>                     .has_with_results(&[digest], &mut results[i..i + 1])
>                     .await;
>                 self.existence_cache.lock().unwrap().insert(digest);
> ```

if `result` has failed it will add the entry to the cache.

if the `results` (which is the result of the digest) fails, it also inserts saying it exists (which would be `None`).

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @allada and @steed924)

___
*[`cas/store/BUILD` line 503 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NieuKpn5JtTZnLWrgYR:-Niho7tgAXENbW33_0ml:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/BUILD#L503)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

Need a line break here.
</blockquote></details>

Done.
___
*[`cas/store/verify_store.rs` line 272 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NieurMY31nYm7TK4ShU:-NihoMSG9W5WAu849Fjx:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/verify_store.rs#L272)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`cas/store/verify_store.rs` line 15 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif7zg05V36VQqZ4MNC:-NihoCX7C72BctUmoPVR:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L15)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use:
https://docs.rs/hashbrown/latest/hashbrown/hash_set/struct.HashSet.html
</blockquote></details>

Done.
___
*[`cas/store/verify_store.rs` line 55 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif91V_AkiEboAJERRE:-NihoE7y6V3VQGjR3jmk:b-67aelv) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L55)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is never called.
</blockquote></details>

Removed as this functionality belongs in completeness_checking_store not existence_store.
___
*[`cas/store/verify_store.rs` line 189 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8akE7paMwiRD5RqW:-NihoLY91jM0ekvnmIRL:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L189)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

if `result` has failed it will add the entry to the cache.

if the `results` (which is the result of the digest) fails, it also inserts saying it exists (which would be `None`).
</blockquote></details>

Done.
___
*[`cas/store/tests/verify_store_test.rs` line 490 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Niev3BN-B7qlhlDhz4a:-NihoNQv01lp7ZU9O5Oi:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/504c1e9190edff5e60908d208b6c74616cee5b70/cas/store/tests/verify_store_test.rs#L490)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @allada, @blakehatch, and @steed924)

___
*[`cas/store/verify_store.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8v7j85Zl6gGZ3TGT:-NihoQLICzOZbE1bMePu:b-t70agf) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L47)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I don't think we want to do existence cache in this store, it should be it's own store.
</blockquote></details>

Moving to a new store wrapper.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @blakehatch and @steed924)

___
*[`cas/store/verify_store.rs` line 55 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif91V_AkiEboAJERRE:-Nijd-_M5DDm33eTl8PA:bq23obg) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L55)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Removed as this functionality belongs in completeness_checking_store not existence_store.
</blockquote></details>

Forget to move it?
___
*[`cas/store/verify_store.rs` line 187 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NijdGjoCAc8QfoFduL9:-NijdGjoCAc8QfoFduLA:b1tqc3b) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/5f2eaacc26c277f880ef43d1b5e4030681b021a8/cas/store/verify_store.rs#L187)):*
> ```XML
>                 let result = self
>                     .pin_inner()
>                     .has_with_results(&[digest], &mut results[i..i + 1])
> ```

We are iterating the digests, then calling `.has_with_results` on each one individually. This function is specifically exposed for stores that can lookup multiple digests at once and return the results with low latency.

I think what makes more sense is to filter and map the digests then do 1 call to `.has_with_results()` then process the results after.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @allada, @blakehatch, and @steed924)

___
*[`cas/store/verify_store.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8v7j85Zl6gGZ3TGT:-NijwX5sDMSy6Zph-32C:bwhglds) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L47)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Moving to a new store wrapper.
</blockquote></details>

Moved.
___
*[`cas/store/verify_store.rs` line 55 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif91V_AkiEboAJERRE:-NijwYsI7E16xBoJpugR:bwhglds) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L55)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Forget to move it?
</blockquote></details>

Moved.
___
*[`cas/store/verify_store.rs` line 189 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nif8akE7paMwiRD5RqW:-NijwgfD3i2iaQzYj0X6:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/825c98905996f95135d58cf651b302fb9371f5eb/cas/store/verify_store.rs#L189)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[`cas/store/verify_store.rs` line 187 at r4](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-NijdGjoCAc8QfoFduL9:-NijwbCY-IJ3RcCEnQgd:b-8eigjr) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/5f2eaacc26c277f880ef43d1b5e4030681b021a8/cas/store/verify_store.rs#L187)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We are iterating the digests, then calling `.has_with_results` on each one individually. This function is specifically exposed for stores that can lookup multiple digests at once and return the results with low latency.

I think what makes more sense is to filter and map the digests then do 1 call to `.has_with_results()` then process the results after.
</blockquote></details>

Restructured has_with_results to be more efficient.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 11 of 13 files reviewed, 12 unresolved discussions (waiting on @allada, @blakehatch, and @steed924)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3JscY674S4-N9XAFa):*
nit: "Add existence cache"
___
*[`cas/store/BUILD` line 35 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3K8OY72ws3xKqQ3uF:-Nj3K8OY72ws3xKqQ3uG:undefined) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/BUILD#L35)):*
> ```Starlark
>         ":shard_store",
>         ":size_partitioning_store",
>         "existence_store",
> ```





_Suggestion:_
```Starlark
:existence_store
```
___
*[`cas/store/existence_store.rs` line 29 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3PjHGAmPJTTD8_kaT:-Nj3PjHGAmPJTTD8_kaU:b-jnp59l) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L29)):*
> ```XML
> pub struct ExistenceStore {
>     inner_store: Arc<dyn StoreTrait>,
>     existence_cache: Arc<Mutex<HashSet<DigestInfo>>>,
> ```

Note: It might be interesting to investigate the use of an `RwLock` in a future commit. Since `HashSet` implements `Send` and `Sync` this should be a drop-in replacement in theory. However, without a benchmark suite we shouldn't attempt these kinds of optimizatons since they could be pessimizations.
___
*[`cas/store/existence_store.rs` line 34 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3LH176gTQAQGyWbo7:-Nj3LH176gTQAQGyWbo8:b8zunm6) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L34)):*
> ```XML
> impl ExistenceStore {
>     pub fn new(inner_store: Arc<dyn StoreTrait>) -> Self {
>         ExistenceStore {
> ```

https://rust-lang.github.io/rust-clippy/master/index.html#/use_self



_Suggestion:_
```XML
Self
```
___
*[`cas/store/existence_store.rs` line 48 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3PNBc381BQR2p13li:-Nj3PNBc381BQR2p13lj:b-bmo3vl) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L48)):*
> ```XML
>         let mut cache = self.existence_cache.lock().await;
>         cache.insert(*digest)
>     }
> ```

nit: Since `digest_in_existence_cache` and `cache_existence` are only used once it seems fine to remove this an inline their implementations in `has_with_results`.
___
*[`cas/store/existence_store.rs` line 70 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3LLv98oSZ2X5utKUp:-Nj3LLv98oSZ2X5utKUq:b-hew2lb) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L70)):*
> ```XML
>         }
> 
>         let not_in_cache: Vec<DigestInfo> = not_in_cache.into_iter().cloned().collect();
> ```

https://rust-lang.github.io/rust-clippy/master/index.html#/cloned_instead_of_copied



_Suggestion:_
```XML
copied
```
___
*[`cas/store/tests/existence_store_test.rs` line 35 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3Qpp1BcWsqfodE6yb:-Nj3Qpp1BcWsqfodE6yc:b-1mfth7) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/tests/existence_store_test.rs#L35)):*
> ```XML
>         let store_owned = ExistenceStore::new(inner_store.clone());
>         let store = Pin::new(&store_owned);
>         const VALUE: &str = "123";
> ```

nit: Put consts in the first line.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383)* status: 11 of 13 files reviewed, 9 unresolved discussions (waiting on @aaronmondal, @allada, and @steed924)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3JscY674S4-N9XAFa):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: "Add existence cache"
</blockquote></details>

Done.
___
*[`cas/store/BUILD` line 35 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3K8OY72ws3xKqQ3uF:-NjADrXA0q43ufLzfb6n:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/BUILD#L35)):*
> ```Starlark
>         ":shard_store",
>         ":size_partitioning_store",
>         "existence_store",
> ```

Done.
___
*[`cas/store/existence_store.rs` line 29 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3PjHGAmPJTTD8_kaT:-NjAAPC0Agxgag9OLIZp:b-pb0gmv) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Note: It might be interesting to investigate the use of an `RwLock` in a future commit. Since `HashSet` implements `Send` and `Sync` this should be a drop-in replacement in theory. However, without a benchmark suite we shouldn't attempt these kinds of optimizatons since they could be pessimizations.
</blockquote></details>

That does seem like an interesting possible optimization compared to a mutex, added a comment to consider it at a later date once there is a benchmark.
___
*[`cas/store/existence_store.rs` line 34 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3LH176gTQAQGyWbo7:-NjABI6dEVoPvAZJLM4G:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L34)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

https://rust-lang.github.io/rust-clippy/master/index.html#/use_self
</blockquote></details>

Done.
___
*[`cas/store/existence_store.rs` line 48 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3PNBc381BQR2p13li:-NjABb9B3_hUtyfIDzG5:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L48)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Since `digest_in_existence_cache` and `cache_existence` are only used once it seems fine to remove this an inline their implementations in `has_with_results`.
</blockquote></details>

Done.
___
*[`cas/store/existence_store.rs` line 70 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3LLv98oSZ2X5utKUp:-NjACxH_CeGwOs4B4-Ed:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/existence_store.rs#L70)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

https://rust-lang.github.io/rust-clippy/master/index.html#/cloned_instead_of_copied
</blockquote></details>

Done.
___
*[`cas/store/tests/existence_store_test.rs` line 35 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-Nj3Qpp1BcWsqfodE6yb:-NjAD75j7NcrUFc5VVr7:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/218d9d8eedb401bf751469136f799bed167abd28/cas/store/tests/existence_store_test.rs#L35)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Put consts in the first line.
</blockquote></details>

Done.

**Review by aaronmondal — COMMENTED** [review]
Why was this removed from the global store list? Will it be added later? ATM we have no docs for this.

> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-:-NjBjra6BRaLMJGGC_FF:bkbzlqk)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @allada and @steed924)

**Review by blakehatch — COMMENTED** [review]
Added back to global store list, was an accident from using one of my stashes from when existence caching was integrated in verify_store instead of it's own store.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-:-NjCvzZL2FM8lzg-OU0w:bfeo6dw)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @aaronmondal, @allada, and @steed924)

**Review by aaronmondal — APPROVED** [review]
:lgtm: :heart: 

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-:-NjGejWGBMQdsQAnue3O:bww7nxd)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @allada and @steed924)

**Review by blakehatch — COMMENTED** [review]
❤️

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/383#-:-NjIElO43acFqEsqHcEO:b3axgw)* status: 11 of 13 files reviewed, 6 unresolved discussions

**Pull request merged**
