### PR TITLE
Add Http2 flags for advanced configurations

### PR DESCRIPTION
**Pull request by allada**
Some users will want to tune advanced http2 configurations. This PR gives that ability.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/365)

### CODE REVIEW

**Review by blakehatch — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/365)* status: all files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`cas/cas_main.rs` line 467 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9fwtY8D5BNyTtaNKG:-Ni9fwtY8D5BNyTtaNKH:b80orpx) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/cas/cas_main.rs#L467)):*
> ```XML
>         if let Some(value) = http_config.http2_max_header_list_size {
>             http.http2_max_header_list_size(value);
>         }
> ```

Would just need another case for the http2_only method here if adding it is of interest.
___
*[`config/cas_server.rs` line 212 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9efww2WTri_0YzAvQ:-Ni9efww2WTri_0YzAvR:b-kibemj) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/config/cas_server.rs#L212)):*
> ```XML
> /// specified.
> #[derive(Deserialize, Debug, Default)]
> pub struct HttpServerConfig {
> ```

https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.http2_only

Only method in the crate not currently supported by this config is http2_only, not necessary for feature completeness here but restricting to just http2 could maybe have it's uses.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/365)* status: all files reviewed, 2 unresolved discussions (waiting on @blakehatch)

___
*[`cas/cas_main.rs` line 467 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9fwtY8D5BNyTtaNKG:-NiAOv_i-kg2VMs8PU2j:b-fqoiyc) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/cas/cas_main.rs#L467)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Would just need another case for the http2_only method here if adding it is of interest.
</blockquote></details>

I thought about it, but decided that it's unlikely to ever be used.
___
*[`config/cas_server.rs` line 212 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9efww2WTri_0YzAvQ:-NiAP8VKAYLih2lTM7Zj:byjlfh8) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/config/cas_server.rs#L212)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.http2_only

Only method in the crate not currently supported by this config is http2_only, not necessary for feature completeness here but restricting to just http2 could maybe have it's uses.
</blockquote></details>

(see above)

**Review by blakehatch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/cas_main.rs` line 467 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9fwtY8D5BNyTtaNKG:-NiGb8Xd34wcu7MLtbDt:bb6un1j) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/cas/cas_main.rs#L467)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I thought about it, but decided that it's unlikely to ever be used.
</blockquote></details>

Done
___
*[`config/cas_server.rs` line 212 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-Ni9efww2WTri_0YzAvQ:-NiGbBvP0nPiC4G2z4bt:bb6un1j) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d6c5376dea5011e879ace382737d981f33769453/config/cas_server.rs#L212)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

(see above)
</blockquote></details>

Done

**Review by blakehatch — APPROVED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/365#-:-NiGbFg862I4PgttLkAn:bb6un1j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
