### PR TITLE
Introduce static executable

### PR DESCRIPTION
**Pull request by aaronmondal**
This allows users to directly build from the repository or to fetch a static release as workflow artifact. The new artifact is fully static and reproducible and should work on all x86_64 systems. We're using a new form of nix caching here that brute-force caches intermediate derivations until the GHA cache blocks additional storage requests, effectively turning the GHA cache into a CAS. Over time this leads to efficient, fine-grained cache utilization that is reusable across different linux runners.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`.gitignore` line 12 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni137Lh5XKLJmNZ_9BH:-Ni137Lh5XKLJmNZ_9BI:bsqvyms) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/.gitignore#L12)):*
> ```ignore
> .direnv/
> .DS_Store
> result
> ```

This is a strange name. Where is this coming from?
___
*[`flake.nix` line 37 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni13Qzp2hFdyZDWv08L:-Ni13Qzp2hFdyZDWv08M:b-bixjxf) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/flake.nix#L37)):*
> ```Nix
>                 env = {
>                   # Create a statically linked executable.
>                   RUSTFLAGS = "-C target-feature=+crt-static";
> ```

fyi: I think if we get away from rusoto, we can remove openssl all together and we won't even need to statically link.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @allada and @MarcusSorealheis)

___
*[`.gitignore` line 12 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni137Lh5XKLJmNZ_9BH:-Ni14JNg2E-VGLbBceuF:bqrc5xm) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/.gitignore#L12)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is a strange name. Where is this coming from?
</blockquote></details>

That's the default name that nix uses for the build output. It's standard, but I can see that this might be confusing. I'm sure it's possible to change the name here, but I wonder whether it's a good idea to change this default. The `result` is a symlink to the nix store location of the last `nix build` target, i.e. it's not necessarily the `cas` executable but could e.g. be a container in `.tar.gz` form.
___
*[`flake.nix` line 37 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni13Qzp2hFdyZDWv08L:-Ni14gg88zZVeI37HSyn:b-4pb8bx) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/flake.nix#L37)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi: I think if we get away from rusoto, we can remove openssl all together and we won't even need to statically link.
</blockquote></details>

Oh I didn't realize that. This makes things much more elegant probably reduces the binary size (current ~22MB) by some significant amount. Let's put this PR on hold until the S3 migration to the aws-sdk is done.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`.gitignore` line 12 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni137Lh5XKLJmNZ_9BH:-Ni17MbU0CiLQrCTYS_K:b-cdz7tu) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/.gitignore#L12)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

That's the default name that nix uses for the build output. It's standard, but I can see that this might be confusing. I'm sure it's possible to change the name here, but I wonder whether it's a good idea to change this default. The `result` is a symlink to the nix store location of the last `nix build` target, i.e. it's not necessarily the `cas` executable but could e.g. be a container in `.tar.gz` form.
</blockquote></details>

This is fine, it is just a bad default name.
___
*[`flake.nix` line 37 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni13Qzp2hFdyZDWv08L:-Ni17TDl5bagXKsKAUaM:bigrd02) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/flake.nix#L37)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Oh I didn't realize that. This makes things much more elegant probably reduces the binary size (current ~22MB) by some significant amount. Let's put this PR on hold until the S3 migration to the aws-sdk is done.
</blockquote></details>

Yeah sounds good. I think technically another package depends on libopenssl, but I believe it can be feature configured to use rustls instead (which is faster from what I've read). I suspect this will reduce the binary size quite a bit.

**Review by aaronmondal — COMMENTED** [review]
Putting this on hold until S3 migration is done.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-:-Ni1ArCx5_XMNy15gqCH:bs3y05o)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @allada and @MarcusSorealheis)

___
*[`.gitignore` line 12 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni137Lh5XKLJmNZ_9BH:-Ni1AnSP7bk65XzAhFW8:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/.gitignore#L12)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is fine, it is just a bad default name.
</blockquote></details>

Done.

**Review by MarcusSorealheis — APPROVED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

**Review by MarcusSorealheis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`flake.nix` line 37 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-Ni13Qzp2hFdyZDWv08L:-Ni3Ye5J0AAVR6T532oW:b-50m9nz) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/653b70355ddb2c7f1fc32908c6e0942cad0fdaa6/flake.nix#L37)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah sounds good. I think technically another package depends on libopenssl, but I believe it can be feature configured to use rustls instead (which is faster from what I've read). I suspect this will reduce the binary size quite a bit.
</blockquote></details>

I'm totally good with holding, though until the aws-sdk work is complete

**Review by allada — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by MarcusSorealheis — APPROVED** [review]
Given the hold, do you want to convert this one to Draft?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/354#-:-NiBUAQB8PLBWgh6xafi:b-z45563)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Comment by aaronmondal** [comment]
Hmm Couldn't convert, but it's fine I'll resend when the other stuff is done. Curious, I thought it was possible to "convert to draft" somewhere.

**Pull request closed without merging**
