### PR TITLE
Fix flakey tests

### PR DESCRIPTION
**Pull request by allada**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@chrisstaite-menlo 

No idea what is going on here. I tried a bunch of stuff. It turns out that `.sync_all()` does a what `.flush()` does internally.

The only thing I can think of is somehow an Arc reference to the internal std::fs::File is somewhere (tokio uses `Arc<std::fs::File>` internally).

But I did some testing on this and it looks like this was not the problem.

It did appear to fix it when I just extraced the `std::fs::File` it fixes it. So no idea.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-:-NeMYE_r1GtpcTIihvH6:benrtrl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
https://github.com/tokio-rs/tokio/issues/2307#issuecomment-618659100 suggests that "`sync_all` + `drop` is working for me (but both are required -- omitting either causes problems)" are we definitely calling `drop` after all `sync_all` calls?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-:-NeMndK1-WtCnaOkSRE6:bvtnp0h)* status: 0 of 6 files reviewed, all discussions resolved

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`cas/worker/tests/local_worker_test.rs` line 400 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNz4nd4fVTA2rn5jtK:-NeNz4nd4fVTA2rn5jtL:b-cec8b0) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/local_worker_test.rs#L400)):*
> ```XML
>                 .await?;
>             file.as_writer().await?.as_mut().sync_all().await?;
>             file.as_writer().await?.flush().await?;
> ```

Unnecessary `flush` after `sync_all`.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 1118 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNzDsxELj45o8vDK4f:-NeNzDsxELj45o8vDK4g:b-81z3ih) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/running_actions_manager_test.rs#L1118)):*
> ```XML
>                 .set_permissions(Permissions::from_mode(0o755))
>                 .await?;
>             test_wrapper_script_handle.flush().await?;
> ```

Should be a `sync_all`
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 1226 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNzJo8BPTaDEa4fmG9:-NeNzJo8BPTaDEa4fmGA:bj44bh5) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/running_actions_manager_test.rs#L1226)):*
> ```XML
>                 .set_permissions(Permissions::from_mode(0o755))
>                 .await?;
>             test_wrapper_script_handle.flush().await?;
> ```

Should a be `sync_all`

**Review by allada — COMMENTED** [review]
Yeah I did a couple tests around this and same results.

I just moved these tests to use the filesystem std api instead.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-:-NeOJaMo3t6a9rzo17Md:bjt5uub)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/tests/local_worker_test.rs` line 400 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNz4nd4fVTA2rn5jtK:-NeOJqAs7cvgOOnUIEk4:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/local_worker_test.rs#L400)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Unnecessary `flush` after `sync_all`.
</blockquote></details>

Done.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 1118 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNzDsxELj45o8vDK4f:-NeOJtD7E8Cvj9cRsfds:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/running_actions_manager_test.rs#L1118)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Should be a `sync_all`
</blockquote></details>

Done.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 1226 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/285#-NeNzJo8BPTaDEa4fmG9:-NeOJtmL5U6l9d8DFnXI:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/1c37fbdc932b0d82bc8b46b306958a18977415b0/cas/worker/tests/running_actions_manager_test.rs#L1226)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Should a be `sync_all`
</blockquote></details>

Done.

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
