### PR TITLE
Always make a copy in MemoryStore to reduce long-lasting allocs

### PR DESCRIPTION
**Pull request by allada**
possibly fix: #289

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/294)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/294#-:-NfKByPd0uM453WS5qJ4:b96vhr1)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/294)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
