### PR TITLE
Move AWS terraform to it's own directory

### PR DESCRIPTION
**Pull request by allada**
This is in prep to support GCP and Azure.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/376)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/376#-:-NiLi82Z-xQqQ8l8K3Uw:b2iyrky)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Comment by MarcusSorealheis** [comment]
I already did this in my PR which will be wrapped up soon.

**Review by allada — COMMENTED** [review]
Yeah, we both need this, to prevent us from stepping on each other, we do it in a separate PR, then we can land independent of each other.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/376#-:-NiLibIfDkc4nCZNFb9f:b-ol2l4p)* status: 0 of 23 files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by MarcusSorealheis — APPROVED** [review]
It's good. I'm going to need to change my PR a bit to work with this but it should be fine.

**Review by allada — COMMENTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Pull request merged**
